name: Build jsc-android and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android:2019-9-4

    steps:
    - uses: actions/checkout@v1

    - name: Install packages
      run: |
        apt-get update
        apt-get install coreutils realpath curl git subversion python3.5 python3.5-dev ruby gperf -y
        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1
        wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
        echo 'export NVM_DIR="$HOME/.nvm"' >> "${HOME}/.bashrc"
        echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm' >> "${HOME}/.bashrc"
        source "${HOME}/.bashrc"
        nvm install 10
        nvm use 10
        nvm alias default 10
      shell: bash

    - name: Install Android packages
      run: |
        sdkmanager \
          "cmake;3.10.2.4988404"
      shell: bash
    - name: Build
      run: |
        yarn clean
        yarn download
        yarn start
      shell: bash

    - name: Archive
      run: |
          mkdir -p archive
          mv dist archive/
          mv dist.unstripped archive/
      shell: bash

    - uses: actions/upload-artifact@v2
      with:
        name: archive
        path: archive


  test:
    needs: build
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/download-artifact@v2
      with:
        name: archive
        path: archive

    - name: Run test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 16
        arch: x86
        disable-animations: false
        script: mv archive/dist . && cd test && yarn && cd android && ./gradlew assembleRelease assembleAndroidTest connectedAndroidTest
